services:
  start-oauth-server:
    build:
      context: ./oauth
      dockerfile: Dockerfile
    container_name: start-oauth-server
    ports:
      - 8080:8080
    networks:
      - start-oauth

  start-oauth-client:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: start-oauth-client
    ports:
      - 3000:3000
    networks:
      - start-oauth

networks:
  start-oauth:
    driver: bridge
